### ISSUE TITLE
Weapon description field wastes space

### ISSUE THREAD

**Issue by joesinghaus** [Bathtor/EPSheet#23]
![weapon desc](https://user-images.githubusercontent.com/18185704/32671586-47f210d6-c648-11e7-93b5-17f9d061a03c.png)

Same problem for psi sleights and maybe other places...
There's a similar problem with Equipment and character traits, where the elements do not use the full width.

**Comment by joesinghaus** [comment]
I notice that you have some whitespace there at the end with a minimum width and flex-grow: 1 - why not let the actual content grow with flex-grow: 1 instead? Seems more useful to me than having eternally growing whitespace.

**Comment by Bathtor** [comment]
I use that whitespace component as a way to push all the other elements together so they only take up the space they need and not more. Sometimes I use it on both sides to centre a component or in between blocks to get even spacing. It's quite versatile really.

However, I concur that in the case of description textareas it maybe doesn't make too much sense.
I'll play around with it a bit and see if I either do as you say and use the textarea to fulfill the same function in the cases where a line ends in a texarea, or I simply always move textareas to their own line and make them take up the whole width of the line. Gotta see what works better.

**Comment by joesinghaus** [comment]
Working nicely now.
