### ISSUE TITLE
Inputs for base aptitudes not wide enough to hold 2-digit numbers

### ISSUE THREAD

**Issue by joesinghaus** [Bathtor/EPSheet#24]
This occurs at least in Windows/Chrome.
![aptitudes](https://user-images.githubusercontent.com/18185704/32671759-e6c80bde-c648-11e7-99aa-c9d6318b77a8.png)

**Comment by joesinghaus** [comment]
If you don't want to make them wider, you could also get rid of the up/down buttons in order to make room.

**Comment by Bathtor** [comment]
Yeah, I've been fighting with this for a quite a while already. I kinda like the up/down buttons, so I don't really want to get rid of them. But they are terribly inconsistent across browsers and operating systems. I'd basically have to add another 0.5em or maybe even 1em of width to accommodate them on every OS/browser combination (which is how they were before I decided to tighten up the calculation for these box widths somewhat).
Alternatively I could dabble with browser selective code, but that is too much micro management for my taste...I like reuse and UI optimisations like that just ruin code reuse.
So I guess my best option is to figure out how much space to account for in the worst browser/OS combo and add that and just live with unnecessarily large boxes on OS X.
