### ISSUE TITLE
Messed-up aptitudes on Firefox

### ISSUE THREAD

**Issue by joesinghaus** [Bathtor/EPSheet#26]
![f3725c54-d92e-4e12-8ee5-87b9429241af](https://user-images.githubusercontent.com/18185704/33044230-6701c37e-ce48-11e7-9f13-5085f27a4689.png)

**Comment by Bathtor** [comment]
damnit...I thought I had finally fixed that^^ Back to work then...

**Comment by joesinghaus** [comment]
Looks like you just need to make the whole right column of the Core tab wider and then increase the width of the first column of this table. No idea why this works differently in Chrome, but tables are a bit mysterious anyway. But it doesn't actually look good in Chrome either with all the first-column labels right-aligned (they just aren't cut off).

... I guess my point was this shouldn't be too much of an effort to fix.

**Comment by Bathtor** [comment]
Yeah, no...There is easily enough space in the right column to accommodate the text. Firefox is calculating the number columns way too large. I purposefully set it up such that the number columns only take up the space they really need and all remaining space goes to the label column, which then properly right aligns as a label column should (come on, who makes a label columns left align? that looks horrible!).
Fixed table layouts seems to be pretty inconsistent across browsers -.-

**Comment by joesinghaus** [comment]
Tables are black magic. Even though this one is an actual table, it doesn't really do what you want. Interestingly, .charsheet .sheet-aptTable th { width: 10%} makes it look much better on FF.

**Comment by Bathtor** [comment]
Yeah...I think I spent like 1h already micro-optimising that width attribute^^
I'll try around with a bunch of browser/OS combinations and see what the best compromise is.

**Comment by Bathtor** [comment]
I noticed that Firefox is just bad at calculating percentages. 11% of 360px is in no world 43px. Switching to em instead avoids the whole issue and makes the table consistent across browsers (at least those I tried).
