### ISSUE TITLE
Suggested visual improvement for e.g. item listings

### ISSUE THREAD

**Issue by joesinghaus** [Bathtor/EPSheet#30]
Suggested changes (for the .sheet-flowPar class): 

font-size: 0.8rem (increase).
line-height: 1.5 (decrease from stupid Roll20 fixed 18px).

**Comment by Bathtor** [comment]
The font-size in 0.8 look ok to me. On my screens I can read it fine in 0.7 and it wastes less space, but if you feel that some people (i.e. you) have problems with that, I would be ok with increasing it to 0.8.

Hmm, line-height 1.5 is an increase in my browser.  I would rather reduce it to to say 1.3?

**Comment by joesinghaus** [comment]
It depends on the system. It looks fine on my Mac, but on my WIndows the 0.7rem looks kind of badly readable. More prominent when space is wasted by too much line-height.

You're right about the line-height, it becomes an increase after bumping up the font size :D. I tested the line-height first, since it was more noticable. Anyway, after a bit more thought, I think 0.7rem and line-height 1.3 or (imo better:) 1.4 are fine. But if you want to make it super readable, bump up the font-size.

**Comment by Bathtor** [comment]
I put 1.4 and 0.7 for now. 
We can revisit the issue if necessary after trying it for a while. I feel that people with worse screens or system fonts, might just as well increase the UI size overall, as many of the other things might be unreadable in that case. But I can't make it optimal for every possible system.
