### ISSUE TITLE
Add roll tags to all roll buttons on the sheet

### ISSUE THREAD

**Issue by joesinghaus** [Bathtor/EPSheet#32]
I know, I know ... but it should really clear up inline roll hover info. The only problem is that translations for these are a bit awkward to do.

**Comment by Bathtor** [comment]
When I have some time...ever ;)

**Comment by Bathtor** [comment]
Should be fixed by 33d5a7c698ab36ab5dd3afdb4c5306a130af1cd0.
Reopen if you find anything important still unlabelled.
