### ISSUE TITLE
Add ToggleField 

### ISSUE THREAD

**Issue by Bathtor** [Bathtor/EPSheet#42]
Since Roll20 expects boolean fields to have `on` for `true` and `0` for `false`, add a field that behaves this way, to allow API to properly interact with checkboxes.

**Comment by joesinghaus** [comment]
Why not set the checkboxes to have value=1? That makes them more sensible to interact with.

**Comment by Bathtor** [comment]
I can do that, too...Doesn't make much difference to the issue. I still have to change the way that boolean values are serialised, and I'm not sure I want to risk existing code breaking by changing my default flag-fields to behave like this.
