### ISSUE TITLE
Aptitude Boni and Morph Bonus

### ISSUE THREAD

**Issue by StarSmythe** [Bathtor/EPSheet#48]
Likely I'm missing something obvious but I cant work out how to input my characters "Morph Bonuses"

**Comment by Bathtor** [comment]
You input them under Aptitude Boni in the Morph tab on a morph in the Morph Bank. They will be applied when you activate that morph (via the checkbox).

I should probably document the allowed formats, though.

**Comment by Bathtor** [comment]
And there we go: [Morph Boni Formats](https://github.com/Bathtor/EPSheet/wiki/Morph-Boni)

From my perspective that solves this issue. 
Please reopen it, if there are still outstanding questions that need addressing.
