### ISSUE TITLE
Translation of the new translation.json

### ISSUE THREAD

**Issue by WallaceMcGregor** [Bathtor/EPSheet#49]
I've translated the new es.json (the last one you did with the skills). I do not know how I found your repository of upgraded sheet but it does not be on the official Roll20 repository. Do you have plans to upgrade the official Roll20 sheet? Do I wait to upload the new translation? Do I give it to you?

**Comment by Bathtor** [comment]
I will eventually push to the official repository again, but I want it tested better, before I do that. I don't like it when people abuse the live players as beta-testers. So I'll be playing this for a few weeks in my campaign before making the decision whether or not it's stable enough to push.
If you are GM and Subscriber you can upload it as a Custom sheet to your campaigns and help test, which will improve my confidence (and allow you to use your updated translation).

Until I do a PR to Roll20, I'll just leave this issue open, so you'll know when to upload your `es.json`. Or you can do a PR to my sheet repo instead and then both will go into the later PR to Roll20, whichever you prefer..

**Comment by WallaceMcGregor** [comment]
I am a Plus user, so I can not upload sheets. However, I am not playing Eclipse Phase yet. I am preparing to a near future when I will play it (not as GM but I am testing things by myself).

I have no problem to wait your PR to Roll20 or do a PR to your sheet repo. Whatever be better for you.

Thanks for the time and answers, and excuse my english.

**Comment by Bathtor** [comment]
It makes no difference for me. 
If you do the PR to my repo now I can close this issue and you can forget about it, and eventually it'll show up on Roll20.
If you want to wait, I'll leave the issue open, and you'll have to remember to pay attention to it when I finally close it.
Either case is pretty much the same for me.

**Comment by Bathtor** [comment]
Actually, I decided to make custom tracking issue for stabilisation (#50), so just use that one of you want to go for option 2 and I'll close this one.
